toggle_key: OFF
matches:

  - trigger: "ffg"
    replace: "Freundliche Grüsse\n\nbpm consult ag\nJan Fader"

  - trigger: "hhotline"
    replace: "Diese Anfrage ist technische Hotline. Bitte an den Hotline-Techniker gemäss Wochenplan stellen."

  - trigger: "ddate"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d.%m.%Y"

  - trigger: "ffstamp"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: "ddatum"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d. %B %Y"

  - trigger: "ttime"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%H:%M"

