toggle_key: OFF
matches:

  - trigger: ":llg"
    replace: "Liebe Grüsse\n\nJan"

  - trigger: ":ffg"
    replace: "Freundliche Grüsse\n\nbpm consult ag\nJan Fader"

  - trigger: "_hhotline"
    replace: "Diese Anfrage ist technische Hotline. Bitte an den Hotline-Techniker gemäss Wochenplan stellen."

  - trigger: ":pprivat"
    replace: "Dein Bedürfnis über das zu reden was dich privat und politisch beschäftigt verstehe ich - jedoch bin ich beruflich und privat so eingespannt, dass ich dir nicht die gewünschte Aufmerksamkeit entgegen bringen kann. Es käme mir daher sehr entgegen wenn wir uns bis auf weiteres auf die Arbeit konzentrieren würden. Vielen Dank dafür"

  - trigger: ":ddate"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d.%m.%Y"

  - trigger: ":ffstamp"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ":ddatum"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d. %B %Y"

  - trigger: ":ttime"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%H:%M"
