matches:

  - trigger: ":llg"
    replace: "Liebe Grüsse\n\nJan"

  - trigger: ":ffg"
    replace: |
             $|$
             Freundliche Grüsse
             Jan Fader

  - triggers: ["Ustü","ustü","UStü"]
    replace: "Unterstützung"

  - trigger: ":ccall"
    replace: "Bitte hierfür gemäss Kommunikationskonzept einen Call erstellen."

  - trigger: ":vdrr"
    replace: "Vielen Dank für Ihre Rückmeldung."

  - trigger: ":kkomm"
    replace: "Deinen Kommentar habe ich leider nur zufällig gesehen, weil ich in diesem Call weder Bearbeiter*in noch Analysierende Drittperson bin."

  - trigger: ":kkw"
    replace: "Die Angabe in KW ist mir unklar, da es mindestens drei unterschiedliche Definitionen für KW gibt. Bitte ein konkretes Datum angeben."

  - trigger: ":nnotfall"
    replace: "Du hast ja diese Woche die Notfallhotline. Bist du in den Queue eingeloggt? Im Wochenplan fehlt dein Eintrag diesbzgl. noch."

  - trigger: ":hhotline"
    replace: "Diese Anfrage ist technische Hotline. Bitte an den Hotline-Techniker gemäss Wochenplan stellen."

  - trigger: ":pprivat"
    replace: "Dein Bedürfnis über das zu reden was dich privat und politisch beschäftigt verstehe ich - jedoch bin ich beruflich und privat so eingespannt, dass ich dir nicht die gewünschte Aufmerksamkeit entgegen bringen kann. Es käme mir daher sehr entgegen wenn wir uns bis auf weiteres auf die Arbeit konzentrieren würden. Vielen Dank dafür"

  - trigger: ":nnaked"
    replace: "Bitte schick mir keine naked pings (https://blogs.gnome.org/markmc/2014/02/20/naked-pings/), sondern nenne immer mindestens ein Thema und/oder einen Call."

  - trigger: ":ddate"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d.%m.%Y"

  - trigger: ":ffstamp"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ":ddatum"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d. %B %Y"

  - trigger: ":ttime"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%H:%M"
